[versions]
junit5 = "6.0.1"
hamcrest = "3.0"
smithy = "1.64.0"
test-logger-plugin = "4.0.0"
spotbugs = "6.0.22"
spotless = "8.1.0"
dep-analysis = "3.5.0"
lang-tool = "6.7"
shadow = "9.2.2"
slf4j = "2.0.17"
jreleaser = "1.21.0"

[libraries]
# Smithy deps
smithy-model = { module = "software.amazon.smithy:smithy-model", version.ref = "smithy" }

# Other deps
langtool-en = { module = "org.languagetool:language-en", version.ref = "lang-tool"}
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

# Test dependencies
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }

# plugin artifacts for buildsrc plugins
test-logger-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "test-logger-plugin" }
spotbugs = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugs" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dep-analysis" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref =  "shadow"}
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }